# basic options
title: My New-blog
author: Unknown person
email: your-email@domain.com
description: A wonderful site
twitter_username: unknown
github_username: xchendgu

# Build settings
markdown: kramdown
theme: minima
