# basic options
title: My New-blog
author: me
email: your-email@domain.com
description: A wonderful site
twitter_username: unkown
github_username: xchendgu

# Build settings
markdown: kramdown
theme: minima
